### ISSUE TITLE
Unable to create a working environment.

### ISSUE THREAD

**Issue by Jezza** [esp-rs/esp-idf-sys#23]
This might link to esp-rs/rust-build#8, as I haven't installed ESP-IDF yet.
But I'm unable to compile libsodium.

![image](https://user-images.githubusercontent.com/4224088/139439168-9f1e5ca4-d59b-427d-9842-079037f98c5e.png)

**Comment by Jezza** [comment]
Ok, after some troubleshooting, it's definitely because I have `cygpath` on my `PATH`.

The problematic code is in [embuild](https://github.com/ivmarkov/embuild/blob/master/src/espidf.rs#L286).
By the looks of it, cygwin (or more specifically, git-bash), does set some env variables that could be looked at, just to make sure the tty is, in fact, from cygwin.

However, that's not all.
That, unfortunately, leads me straight into another issue.
Whether I patch `embuild` or if I run it directly from mingw64, the issue is the same:

![image](https://user-images.githubusercontent.com/4224088/139488301-73f70b81-469b-4095-a6a0-079fd2597c7d.png)

![image](https://user-images.githubusercontent.com/4224088/139488416-ae9098dd-2873-43a0-93c5-fe5df15ff25d.png)

I'm going to assume the -I arg is wrong, so I'll start looking through them.

**Comment by Jezza** [comment]
Weird.
Maybe a symlink was supposed to be generated.

![image](https://user-images.githubusercontent.com/4224088/139489068-6f7845fc-0359-4130-a75e-b097d8438387.png)

I've found the files, but the includes are pointing to a completely different location.

**Comment by N3xed** [comment]
I think you're running into windows path length limitations: see [Microsoft docs](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd).

**Comment by N3xed** [comment]
> Ok, after some troubleshooting, it's definitely because I have `cygpath` on my `PATH`.
> 
> The problematic code is in [embuild](https://github.com/ivmarkov/embuild/blob/master/src/espidf.rs#L286). By the looks of it, cygwin (or more specifically, git-bash), does set some env variables that could be looked at, just to make sure the tty is, in fact, from cygwin.

I've created a new release that should fix this issue. I guess the first workaround that I implemented to circumvent issues with msys or cygwin on Windows was not that great, but these problems should be fixed now.

**Comment by Jezza** [comment]
Weird, even after setting the long paths flag, I'm still getting the same error.

I played around with it a bit and got a new error:
![image](https://user-images.githubusercontent.com/4224088/139555072-78474b66-c477-471b-a398-922601878a03.png)

**Comment by N3xed** [comment]
> I played around with it a bit and got a new error: ![image](https://user-images.githubusercontent.com/4224088/139555072-78474b66-c477-471b-a398-922601878a03.png)
> 
> I'm a bit lost with this one though...

This error is unrelated, I'm not sure how it happens but I fixed it by just copying the other binaries (like cargo, 
cargo-clippy, cargo-fmt, clippy-driver and rustfmt) from the nightly toolchain to the esp toolchain. I think it has to do with cargo concurrently linking to these executables (the nightly ones are used if the used toolchain doesn't have them).

**Comment by georgik** [comment]
@Jezza The first error is caused by too long build path. Move the project to shorter path. This is known limitation of Windows build via Platform IO.

**Comment by Jezza** [comment]
@georgik I'm not building it by platform io anymore.
I also ended up enabling long paths in windows.

The current issue is still [this one](https://user-images.githubusercontent.com/4224088/139488301-73f70b81-469b-4095-a6a0-079fd2597c7d.png).

**Comment by georgik** [comment]
Just FYI @Jezza Long Paths on Windows does not solve the problem. For some unknown reason this setting is ignored the build.

**Comment by Jezza** [comment]
Ah, I see.
Nice to know.

**Comment by N3xed** [comment]
With a little bit of [research](https://gitlab.kitware.com/cmake/cmake/-/issues/19675) this seems to be a `gcc` limitation. 

Possible workarounds:
- Use [`subst`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/subst) to assign a virtual drive letter to a path (should work as pointed out [here](https://stackoverflow.com/questions/7866387/git-mingw32-and-long-path-file-names-under-windows)).
- Create a directory junction (with [`mklink /j`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink)) to shorten the path (not tested).
- Moving the project to a directory with a shorter path.

If this is a common issue, it may be worth trying to implement a workaround (for example forcing cmake to use relative paths, creating directory junctions ourselves, etc.).

**Comment by MabezDev** [comment]
Closing due to inactivity, I hope that by now all the issues are resolved. Please file another if this is not the case.
